package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.junit.Test;

public class DeleteGroupTest extends TestBase {

  @Test
  public void testDeleteGroup() {
    goToGroups();
    selectGroup();
    deleteSelectedGroups();
    returnToGroupPage();
  }

}
