package ru.stqa.pft.addressbook;// Generated by Selenium IDE
import org.junit.Test;


public class GroupCreation extends TestBase {

  @Test
  public void testGroupCreation() {

    goToGroups();
    initNewGroup();
    fillGroupFields(new GroupData("test2", "test3", "test4"));
    submitGroupCreation();
    returnToGroupPage();
  }

}
