package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import ru.stqa.pft.addressbook.model.GroupData;


public class GroupCreation extends TestBase {

  @Test
  public void testGroupCreation() {
    app.getNavigationHelper().goToGroups();
    int before = app.getGroupHelper().getGroupCount();
    app.getGroupHelper().createGroup(new GroupData("test1", "test2", "test3"));
    int after = app.getGroupHelper().getGroupCount();
    Assert.assertEquals(after, before + 1);
  }

}
