package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;
import ru.stqa.pft.addressbook.model.GroupData;


public class GroupCreation extends TestBase {

  @Test
  public void testGroupCreation() {

    app.goToGroups();
    app.initNewGroup();
    app.fillGroupFields(new GroupData("test2", "test3", "test4"));
    app.submitGroupCreation();
    app.returnToGroupPage();
  }

}
